/**
 * Fixtures for UI development and tests.
 *
 * Mirrors the real Chase Sapphire Reserve screenshots so presentational work
 * can proceed against believable data before the catalog and query layer land.
 * Not seeded, not shipped to the database — import only from components in
 * development, stories, and tests.
 */
import type { CardVM, CatalogEntryVM, TrackerVM } from '@/lib/view-models';

export const csrFixture: CardVM = {
  userCardId: 'fixture-csr',
  slug: 'chase-sapphire-reserve',
  name: 'Chase Sapphire Reserve®',
  shortName: 'Sapphire Reserve',
  issuerDisplayName: 'Chase',
  issuerBrandColor: '#117ACA',
  network: 'VISA',
  last4: null,
  art: {
    gradient: ['#0B1A2B', '#12283F', '#1D3A57'],
    pattern: 'guilloche',
    textColor: '#F2F4F7',
    chipColor: '#C9A227',
  },
  annualFeeLabel: '$795',
  aprLabel: '19.49% - 27.99%',
  foreignTxFeeLabel: 'None',
  dataAsOf: '2026-08-24',
  sourceUrl: 'https://www.chase.com/personal/credit-cards/sapphire/reserve',
  pointsCurrencyName: 'Chase Ultimate Rewards',
  redemptionMethod: 'DEFAULT',
  centsPerPointLabel: '1.5¢ per point',
  rewards: [
    {
      multiplierLabel: '8x',
      category: 'at Chase Ultimate Rewards (Rental Cars, Hotels, Dining)',
      description: 'Earn 8x points on all purchases through Chase Travel℠.',
    },
    {
      multiplierLabel: '5x',
      category: 'at Lyft',
      description: '5x points per $1 on qualifying Lyft rides through 03/2027.',
      endsOn: '2027-03-31',
    },
    {
      multiplierLabel: '4x',
      category: 'on Airlines, Hotels',
      description: '4x points on flights and hotels booked directly.',
    },
    { multiplierLabel: '3x', category: 'on Dining', description: '3x points on dining worldwide.' },
    {
      multiplierLabel: '1x',
      category: 'on Everywhere',
      description: '1x point per $1 spent on all other eligible purchases.',
    },
  ],
  redeemable: [
    {
      slug: 'csr-annual-travel-credit',
      kind: 'STATEMENT_CREDIT',
      title: '$300 Annual Travel Credit',
      shortTitle: 'Annual Travel Credit',
      description: 'Automatically applied to the first $300 of travel purchases each cardmember year.',
      brandKey: 'ultimate-rewards',
      cadenceLabel: '$300 per year',
      isHighlighted: true,
      currentPeriod: {
        id: null,
        start: '2026-03-15',
        end: '2027-03-15',
        label: '2026 Cardmember Year',
        status: 'open',
        valueCents: 30000,
        usedCents: 0,
        remainingCents: 30000,
        percentUsed: 0,
        daysLeft: 203,
      },
    },
    {
      slug: 'csr-the-edit-credit',
      kind: 'STATEMENT_CREDIT',
      title: 'Up to $500 Annual Statement Credit at The Edit',
      shortTitle: 'The Edit Hotel Credit',
      description: 'Statement credits on prepaid bookings at The Edit hotel collection.',
      brandKey: 'travel',
      cadenceLabel: '$500 per year',
      isHighlighted: true,
      currentPeriod: {
        id: null,
        start: '2026-01-01',
        end: '2027-01-01',
        label: '2026',
        status: 'open',
        valueCents: 50000,
        usedCents: 25000,
        remainingCents: 25000,
        percentUsed: 50,
        daysLeft: 130,
      },
    },
    {
      slug: 'csr-sapphire-dining',
      kind: 'STATEMENT_CREDIT',
      title: 'Up to $300 back on dining at Sapphire Reserve Exclusive Tables',
      shortTitle: 'Exclusive Tables Dining',
      description: 'Up to $150 in statement credits each half of the calendar year.',
      brandKey: 'opentable',
      cadenceLabel: '$150 twice a year • $300 total',
      isHighlighted: true,
      currentPeriod: {
        id: null,
        start: '2026-07-01',
        end: '2027-01-01',
        label: 'Jul–Dec 2026',
        status: 'open',
        valueCents: 15000,
        usedCents: 0,
        remainingCents: 15000,
        percentUsed: 0,
        daysLeft: 130,
      },
    },
  ],
  other: [
    {
      slug: 'csr-ihg-diamond',
      kind: 'SPEND_THRESHOLD',
      title: 'IHG One Rewards Diamond Elite Status after $75,000 in spend annually',
      shortTitle: 'IHG Diamond Elite',
      description:
        'Spend $75,000 in a calendar year on your Chase Sapphire Reserve to unlock IHG One Rewards Diamond Elite status.',
      cadenceLabel: '$75,000 annual spend',
      isHighlighted: false,
      currentPeriod: {
        id: null,
        start: '2026-01-01',
        end: '2027-01-01',
        label: '2026',
        status: 'open',
        valueCents: 7500000,
        usedCents: 1840000,
        remainingCents: 5660000,
        percentUsed: 24,
        daysLeft: 130,
      },
    },
    {
      slug: 'csr-hyatt-explorist',
      kind: 'SPEND_THRESHOLD',
      title: 'World of Hyatt Explorist Status after $75,000 in annual spend',
      shortTitle: 'Hyatt Explorist',
      description:
        'Spend $75,000 on your Chase Sapphire Reserve in a calendar year to receive World of Hyatt Explorist status.',
      cadenceLabel: '$75,000 annual spend',
      isHighlighted: false,
      currentPeriod: {
        id: null,
        start: '2026-01-01',
        end: '2027-01-01',
        label: '2026',
        status: 'open',
        valueCents: 7500000,
        usedCents: 1840000,
        remainingCents: 5660000,
        percentUsed: 24,
        daysLeft: 130,
      },
    },
    {
      slug: 'csr-priority-pass',
      kind: 'PERK',
      title: 'Priority Pass™ Select lounge access',
      shortTitle: 'Priority Pass',
      description: 'Complimentary membership with access to 1,300+ airport lounges worldwide.',
      cadenceLabel: 'Ongoing',
      isHighlighted: false,
      currentPeriod: null,
    },
  ],
  roi: {
    annualFeeCents: 79500,
    capturedCents: 25000,
    addressableToDateCents: 95000,
    claimableNowCents: 70000,
    forfeitedCents: 15000,
    unopenedCents: 0,
    annualFaceValueCents: 110000,
    netCents: -54500,
    projectedNetCents: 15500,
    isWorthItToday: false,
  },
};

export const emptyTrackerFixture: TrackerVM = {
  groups: [],
  totals: {
    capturedCents: 0,
    addressableToDateCents: 0,
    claimableNowCents: 0,
    forfeitedCents: 0,
    unopenedCents: 0,
    annualFaceValueCents: 0,
  },
};

export const catalogFixture: CatalogEntryVM[] = [
  {
    slug: 'chase-sapphire-reserve',
    name: 'Chase Sapphire Reserve®',
    shortName: 'Sapphire Reserve',
    issuerDisplayName: 'Chase',
    network: 'VISA',
    annualFeeLabel: '$795',
    art: csrFixture.art,
    benefitCount: 6,
    alreadyInWallet: false,
  },
  {
    slug: 'capital-one-venture-x',
    name: 'Capital One Venture X Rewards Credit Card',
    shortName: 'Venture X',
    issuerDisplayName: 'Capital One',
    network: 'VISA',
    annualFeeLabel: '$395',
    art: {
      gradient: ['#1C1C1E', '#2C2C2E', '#3A3A3C'],
      pattern: 'sheen',
      textColor: '#F5F5F7',
      chipColor: '#B8B8BD',
    },
    benefitCount: 4,
    alreadyInWallet: false,
  },
];
