import type { SeedCard } from '../types';

const card: SeedCard = {
  slug: 'chase-sapphire-reserve',
  issuer: 'chase',
  name: 'Chase Sapphire Reserve®',
  shortName: 'Sapphire Reserve',
  network: 'VISA',
  annualFeeCents: 79500,
  aprLowBps: 1949,
  aprHighBps: 2999,
  foreignTxFeeBps: null,
  pointsCurrency: 'chase-ultimate-rewards',
  art: {
    gradient: ['#0B1B33', '#1E3A5F', '#54708C'],
    pattern: 'guilloche',
    textColor: '#F5F7FA',
    chipColor: '#C9A227',
  },
  dataAsOf: '2026-08-24',
  sourceUrl: 'https://creditcards.chase.com/rewards-credit-cards/sapphire/reserve',
  rewards: [
    {
      multiplierX100: 800,
      category: 'Chase Travel℠ (including The Edit℠)',
      description: 'Earn 8x points on all purchases booked through Chase Travel℠, including The Edit℠.',
    },
    {
      multiplierX100: 400,
      category: 'Flights & Hotels Booked Direct',
      description: 'Earn 4x points on flights and hotels booked directly with the airline or hotel.',
    },
    {
      multiplierX100: 300,
      category: 'Dining Worldwide',
      description: 'Earn 3x points on dining worldwide.',
    },
    {
      multiplierX100: 100,
      category: 'All Other Purchases',
      description: 'Earn 1x points on all other purchases.',
    },
  ],
  benefits: [
    {
      slug: 'csr-annual-travel-credit',
      title: '$300 Annual Travel Credit',
      shortTitle: 'Travel Credit',
      description:
        'Up to $300 in statement credits each cardmember year, applied automatically against the first $300 of travel purchases. The credit resets at the close of the first statement after your account-open anniversary, not on January 1.',
      brandKey: 'chase-travel',
      type: 'STATEMENT_CREDIT',
      valueCents: 30000,
      cadence: 'ANNUAL',
      resetBasis: 'STATEMENT_ANNIVERSARY',
      isHighlighted: true,
    },
    {
      slug: 'csr-the-edit-hotel-credit',
      title: '$500 The Edit℠ Hotel Credit',
      shortTitle: 'The Edit Credit',
      description:
        'Up to $500 in automatic statement credits per calendar year on prepaid stays at The Edit℠ by Chase Travel properties, capped at $250 per booking with a two-night minimum. As of 2026 both $250 credits can be used any time during the year rather than in fixed six-month windows.',
      brandKey: 'chase-travel',
      type: 'STATEMENT_CREDIT',
      valueCents: 50000,
      cadence: 'ANNUAL',
      resetBasis: 'CALENDAR',
      isHighlighted: true,
    },
    {
      slug: 'csr-dining-credit',
      title: '$300 Sapphire Reserve Exclusive Tables Dining Credit',
      shortTitle: 'Dining Credit',
      description:
        'Up to $150 in statement credits twice per calendar year (January–June and July–December) at restaurants in the Sapphire Reserve Exclusive Tables collection, enrolled through OpenTable. Unused halves do not roll over.',
      brandKey: 'opentable',
      type: 'STATEMENT_CREDIT',
      valueCents: 15000,
      cadence: 'SEMIANNUAL',
      resetBasis: 'CALENDAR',
      isHighlighted: true,
    },
    {
      slug: 'csr-stubhub-credit',
      title: '$300 StubHub & viagogo Credit',
      shortTitle: 'StubHub Credit',
      description:
        'Up to $150 in statement credits twice per calendar year (January–June and July–December) on event tickets purchased through StubHub.com and viagogo.com. Unused halves do not roll over.',
      brandKey: 'stubhub',
      type: 'STATEMENT_CREDIT',
      valueCents: 15000,
      cadence: 'SEMIANNUAL',
      resetBasis: 'CALENDAR',
    },
    {
      slug: 'csr-select-hotels-credit-2026',
      title: '$250 Select Hotels Credit (2026 only)',
      shortTitle: 'Select Hotels Credit',
      description:
        'Up to $250 in statement credits on two-night-minimum stays at select hotel brands (IHG, Montage, Pendry, Omni, Virgin Hotels, Minor Hotels, Pan Pacific) booked through Chase Travel℠ between January 1 and December 31, 2026. Announced as a 2026-only benefit, not a permanent one.',
      brandKey: 'chase-travel',
      type: 'STATEMENT_CREDIT',
      valueCents: 25000,
      cadence: 'ONE_TIME',
      resetBasis: 'FIXED_WINDOW',
      windowStart: '2026-01-01',
      windowEnd: '2026-12-31',
    },
    {
      slug: 'csr-lyft-credit',
      title: '$120 Annual Lyft Credit',
      shortTitle: 'Lyft Credit',
      description: 'Up to $10 in in-app Lyft credit each month, worth up to $120 per year.',
      brandKey: 'lyft',
      type: 'STATEMENT_CREDIT',
      valueCents: 1000,
      cadence: 'MONTHLY',
      resetBasis: 'CALENDAR',
    },
    {
      slug: 'csr-doordash-credit',
      title: 'DoorDash DashPass & Monthly Credits',
      shortTitle: 'DoorDash Credits',
      description:
        'Complimentary DashPass membership plus up to $25 per month in DoorDash credits: a $5 monthly restaurant credit and two $10 monthly promo credits usable on grocery, retail and other non-restaurant orders.',
      brandKey: 'doordash',
      type: 'STATEMENT_CREDIT',
      valueCents: 2500,
      cadence: 'MONTHLY',
      resetBasis: 'CALENDAR',
    },
    {
      slug: 'csr-peloton-credit',
      title: '$120 Annual Peloton Credit',
      shortTitle: 'Peloton Credit',
      description: 'Up to $10 in statement credits each month toward a Peloton membership, worth up to $120 per year.',
      brandKey: 'peloton',
      type: 'STATEMENT_CREDIT',
      valueCents: 1000,
      cadence: 'MONTHLY',
      resetBasis: 'CALENDAR',
    },
    {
      slug: 'csr-apple-subscriptions',
      title: 'Complimentary Apple TV+ and Apple Music',
      shortTitle: 'Apple Subscriptions',
      description:
        'Complimentary Apple TV+ and Apple Music subscriptions, offered through June 22, 2027. Activation required through your Chase account.',
      brandKey: 'apple',
      type: 'PERK',
      cadence: 'ONE_TIME',
      resetBasis: 'FIXED_WINDOW',
      windowEnd: '2027-06-22',
    },
    {
      slug: 'csr-global-entry-credit',
      title: 'Global Entry, TSA PreCheck® or NEXUS Credit',
      shortTitle: 'Global Entry Credit',
      description:
        'Up to $120 in statement credits toward a Global Entry, TSA PreCheck® or NEXUS application fee, once every four years.',
      type: 'STATEMENT_CREDIT',
      valueCents: 12000,
      cadence: 'EVERY_N_YEARS',
      resetBasis: 'CALENDAR',
      everyNYears: 4,
    },
    {
      slug: 'csr-priority-pass-select',
      title: 'Priority Pass™ Select Lounge Access',
      shortTitle: 'Lounge Access',
      description:
        'Complimentary Priority Pass™ Select membership with access to over 1,300 airport lounges worldwide after enrollment.',
      brandKey: 'priority-pass',
      type: 'PERK',
      cadence: 'NONE',
      resetBasis: 'CALENDAR',
    },
    {
      slug: 'csr-ihg-platinum-status',
      title: 'IHG One Rewards Platinum Elite Status',
      shortTitle: 'IHG Platinum',
      description:
        'Complimentary IHG One Rewards Platinum Elite status after activation — a tier that otherwise requires 40 qualifying nights in a calendar year.',
      brandKey: 'ihg',
      type: 'PERK',
      cadence: 'NONE',
      resetBasis: 'CALENDAR',
    },
    {
      slug: 'csr-ihg-diamond-75k-spend',
      title: 'IHG One Rewards Diamond Elite at $75,000 Spend',
      shortTitle: 'IHG Diamond at $75k',
      description:
        'Spend $75,000 on the card in a calendar year to unlock top-tier IHG One Rewards Diamond Elite status.',
      brandKey: 'ihg',
      type: 'SPEND_THRESHOLD',
      thresholdCents: 7500000,
      cadence: 'ANNUAL',
      resetBasis: 'CALENDAR',
    },
    {
      slug: 'csr-southwest-a-list-75k-spend',
      title: 'Southwest A-List Status + $500 Southwest Credit at $75,000 Spend',
      shortTitle: 'Southwest at $75k',
      description:
        'Spend $75,000 on the card in a calendar year to unlock Southwest Airlines A-List status plus a $500 Southwest airfare credit when booked through Chase Travel℠.',
      brandKey: 'southwest',
      type: 'SPEND_THRESHOLD',
      thresholdCents: 7500000,
      cadence: 'ANNUAL',
      resetBasis: 'CALENDAR',
    },
    {
      slug: 'csr-shops-at-chase-75k-spend',
      title: '$250 The Shops at Chase Credit at $75,000 Spend',
      shortTitle: 'Shops at Chase at $75k',
      description:
        'Spend $75,000 on the card in a calendar year to unlock a $250 credit for The Shops at Chase.',
      brandKey: 'chase',
      type: 'SPEND_THRESHOLD',
      thresholdCents: 7500000,
      cadence: 'ANNUAL',
      resetBasis: 'CALENDAR',
    },
  ],
};

export default card;
